[package]
name = "newslatter"
version = "0.1.0"
authors = ["James Muriuki <geniusinrust@gmail.com"]
edition = "2024"

[dependencies]
actix-web = "4.11.0"
reqwest = "0.12.24"
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread"]}

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name= "newslatter"